pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                echo 'Building stage'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
                echo 'Testing stage'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}

